apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    creationTimestamp: null
    name: sriov-network-operator.v4.12.0-202304070941-sriov-ne-85bc6d65cf
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: sriov-network-operator.v4.12.0-202304070941-sriov-ne-85bc6d65cf
subjects:
    - kind: ServiceAccount
      name: sriov-network-config-daemon
      namespace: openshift-sriov-network-operator
