apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        alm-examples: |-
            [
              {
                "apiVersion": "sriovnetwork.openshift.io/v1",
                "kind": "SriovIBNetwork",
                "metadata": {
                  "name": "example-sriovibnetwork",
                  "namespace": "openshift-sriov-network-operator"
                },
                "spec": {
                  "ipam": "{\n  \"type\": \"host-local\",\n  \"subnet\": \"10.56.217.0/24\",\n  \"rangeStart\": \"10.56.217.171\",\n  \"rangeEnd\": \"10.56.217.181\",\n  \"routes\": [{\n    \"dst\": \"0.0.0.0/0\"\n  }],\n  \"gateway\": \"10.56.217.1\"\n}\n",
                  "linkState": "auto",
                  "networkNamespace": "default",
                  "resourceName": "mellanoxnics"
                }
              },
              {
                "apiVersion": "sriovnetwork.openshift.io/v1",
                "kind": "SriovNetwork",
                "metadata": {
                  "name": "example-sriovnetwork",
                  "namespace": "openshift-sriov-network-operator"
                },
                "spec": {
                  "ipam": "{\n  \"type\": \"host-local\",\n  \"subnet\": \"10.56.217.0/24\",\n  \"rangeStart\": \"10.56.217.171\",\n  \"rangeEnd\": \"10.56.217.181\",\n  \"routes\": [{\n    \"dst\": \"0.0.0.0/0\"\n  }],\n  \"gateway\": \"10.56.217.1\"\n}\n",
                  "networkNamespace": "default",
                  "resourceName": "intelnics",
                  "spoofChk": "on",
                  "trust": "off",
                  "vlan": 0
                }
              },
              {
                "apiVersion": "sriovnetwork.openshift.io/v1",
                "kind": "SriovNetworkNodePolicy",
                "metadata": {
                  "name": "policy-1",
                  "namespace": "openshift-sriov-network-operator"
                },
                "spec": {
                  "deviceType": "vfio-pci",
                  "mtu": 9000,
                  "nicSelector": {
                    "pfNames": [
                      "eth1"
                    ],
                    "rootDevices": [
                      "0000:01:00.1"
                    ],
                    "vendor": "8086"
                  },
                  "nodeSelector": {
                    "feature.node.kubernetes.io/network-sriov.capable": "true"
                  },
                  "numVfs": 6,
                  "priority": 99,
                  "resourceName": "intelnics"
                }
              },
              {
                "apiVersion": "sriovnetwork.openshift.io/v1",
                "kind": "SriovNetworkNodeState",
                "metadata": {
                  "name": "minikube",
                  "namespace": "openshift-sriov-network-operator"
                },
                "spec": {
                  "interfaces": []
                }
              },
              {
                "apiVersion": "sriovnetwork.openshift.io/v1",
                "kind": "SriovNetworkPoolConfig",
                "metadata": {
                  "name": "sriovnetworkpoolconfig-sample"
                },
                "spec": {
                  "foo": "bar"
                }
              },
              {
                "apiVersion": "sriovnetwork.openshift.io/v1",
                "kind": "SriovOperatorConfig",
                "metadata": {
                  "name": "default",
                  "namespace": "openshift-sriov-network-operator"
                },
                "spec": {
                  "enableInjector": true,
                  "enableOperatorWebhook": true,
                  "logLevel": 2
                }
              }
            ]
        capabilities: Basic Install
        categories: Networking
        certified: "false"
        containerImage: quay.io/pliurh/sriov-network-operator-manager:bd1
        createdAt: 2019/04/30
        description: An operator for configuring SR-IOV components and initializing SRIOV network devices in Openshift cluster.
        olm.skipRange: '>=4.3.0-0 <4.12.0-202304070941'
        olm.targetNamespaces: openshift-sriov-network-operator
        operatorframework.io/suggested-namespace: openshift-sriov-network-operator
        operators.openshift.io/infrastructure-features: '["disconnected", "cni"]'
        operators.openshift.io/valid-subscription: '["OpenShift Kubernetes Engine", "OpenShift Container Platform", "OpenShift Platform Plus"]'
        operators.operatorframework.io/builder: operator-sdk-v1.23.0
        operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
        repository: https://github.com/k8snetworkplumbingwg/sriov-network-operator
        support: Red Hat
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
    creationTimestamp: null
    labels:
        control-plane: controller-manager
    name: sriov-network-operator
    namespace: openshift-sriov-network-operator
spec:
    replicas: 1
    selector:
        matchLabels:
            name: sriov-network-operator
    strategy: {}
    template:
        metadata:
            annotations:
                target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
            creationTimestamp: null
            labels:
                name: sriov-network-operator
        spec:
            containers:
                - args:
                    - --leader-elect
                  command:
                    - sriov-network-operator
                  env:
                    - name: WATCH_NAMESPACE
                      valueFrom:
                        fieldRef:
                            fieldPath: metadata.annotations['olm.targetNamespaces']
                    - name: SRIOV_CNI_IMAGE
                      value: registry.redhat.io/openshift4/ose-sriov-cni@sha256:bf880039b2408b5dc1e2d5ba4b75f54262f71d828e0b5ec05dc960137ab59c47
                    - name: SRIOV_DEVICE_PLUGIN_IMAGE
                      value: registry.redhat.io/openshift4/ose-sriov-network-device-plugin@sha256:1da1cb9d3d49ec0f59e96dc7405fd0aa878766709a24f9323725522b86093e13
                    - name: NETWORK_RESOURCES_INJECTOR_IMAGE
                      value: registry.redhat.io/openshift4/ose-sriov-dp-admission-controller@sha256:95a0eb464555f2cb15256ce24036cab09ae4f9be152d021bc89ebb4aa5df4c9b
                    - name: OPERATOR_NAME
                      value: sriov-network-operator
                    - name: SRIOV_NETWORK_CONFIG_DAEMON_IMAGE
                      value: registry.redhat.io/openshift4/ose-sriov-network-config-daemon@sha256:42877448784acdaf710d1a8cd438a3757755f5131016f19c84be137f9afcc940
                    - name: SRIOV_NETWORK_WEBHOOK_IMAGE
                      value: registry.redhat.io/openshift4/ose-sriov-network-webhook@sha256:19d51d3f43ffdb6b05248f96229c83c096ceecd9374af3eb6986f564887d02a5
                    - name: SRIOV_INFINIBAND_CNI_IMAGE
                      value: registry.redhat.io/openshift4/ose-sriov-infiniband-cni@sha256:9624caa36a51da6e8058a6050d0da5a6bad98b2126084e9a8913399296aa21bf
                    - name: RESOURCE_PREFIX
                      value: openshift.io
                    - name: ENABLE_ADMISSION_CONTROLLER
                      value: "true"
                    - name: NAMESPACE
                      valueFrom:
                        fieldRef:
                            fieldPath: metadata.namespace
                    - name: NODE_NAME
                      valueFrom:
                        fieldRef:
                            fieldPath: spec.nodeName
                    - name: POD_NAME
                      valueFrom:
                        fieldRef:
                            fieldPath: metadata.name
                    - name: RELEASE_VERSION
                      value: 4.12.0
                  image: registry.redhat.io/openshift4/ose-sriov-network-operator@sha256:aceed421acc1b29282380d379adc52cd414017e4ca2991f1178061fe858cffc0
                  imagePullPolicy: IfNotPresent
                  livenessProbe:
                    httpGet:
                        path: /healthz
                        port: 8081
                    initialDelaySeconds: 15
                    periodSeconds: 20
                  name: sriov-network-operator
                  readinessProbe:
                    httpGet:
                        path: /readyz
                        port: 8081
                    initialDelaySeconds: 5
                    periodSeconds: 10
                  resources: {}
            nodeSelector:
                node-role.kubernetes.io/master: ""
            serviceAccountName: sriov-network-operator
            tolerations:
                - effect: NoSchedule
                  key: node-role.kubernetes.io/master
                  operator: Exists
