apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    creationTimestamp: null
    name: sriov-network-operator.v4.12.0-202304070941-sriov-ne-7f4c8c89c4
    namespace: openshift-sriov-network-operator
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: sriov-network-operator.v4.12.0-202304070941-sriov-ne-7f4c8c89c4
subjects:
    - kind: ServiceAccount
      name: sriov-network-operator
      namespace: openshift-sriov-network-operator
