apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    creationTimestamp: null
    name: sriov-network-operator.v4.12.0-202304070941-sriov-ne-56565fcf78
    namespace: openshift-sriov-network-operator
rules:
    - apiGroups:
        - ""
      resources:
        - pods
      verbs:
        - '*'
    - apiGroups:
        - apps
      resources:
        - daemonsets
      verbs:
        - '*'
    - apiGroups:
        - sriovnetwork.openshift.io
      resources:
        - '*'
        - sriovnetworknodestates
      verbs:
        - '*'
    - apiGroups:
        - security.openshift.io
      resourceNames:
        - privileged
      resources:
        - securitycontextconstraints
      verbs:
        - use
    - apiGroups:
        - ""
      resources:
        - configmaps
      verbs:
        - get
        - update
    - apiGroups:
        - coordination.k8s.io
      resources:
        - leases
      verbs:
        - '*'
