apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    creationTimestamp: null
    name: sriov-network-operator.v4.12.0-202304070941-sriov-ne-56565fcf78
    namespace: openshift-sriov-network-operator
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: sriov-network-operator.v4.12.0-202304070941-sriov-ne-56565fcf78
subjects:
    - kind: ServiceAccount
      name: sriov-network-config-daemon
      namespace: openshift-sriov-network-operator
