apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: operators
policies:
- manifests:
  - path: ptp-operator.4.12.0-202304111715
  - path: local-storage-operator.v4.12.0-202304111715
  - path: cluster-logging.v5.6.4
  - path: sriov-network-operator.v4.12.0-202304070941
  name: operators
  placement:
    clusterSelector:
      matchExpressions:
      - key: common-cnfdf01
        operator: In
        values:
        - "true"
policyDefaults:
  namespace: cnfdf01-common
  placement: {}
  policyAnnotations:
    ran.openshift.io/ztp-deploy-wave: "1"
