apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: accelerator-discovery
  name: accelerator-discovery
  namespace: openshift-sriov-fec
spec:
  minReadySeconds: 10
  selector:
    matchLabels:
      app: accelerator-discovery
  template:
    metadata:
      labels:
        app: accelerator-discovery
      name: accelerator-discovery
    spec:
      serviceAccount: accelerator-discovery
      serviceAccountName: accelerator-discovery
      containers:
      - image: registry.connect.redhat.com/intel/n3000-labeler@sha256:b3d5c2ec1d50e95c5bef0d0b246afebd4969d29c70dd3497236203f232ba5706
        imagePullPolicy: IfNotPresent
        name: accelerator-discovery
        securityContext:
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: config-volume
          mountPath: "/labeler-workspace/config"
          readOnly: true
        env:
          - name: NODENAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
      volumes:
        - name: config-volume
          configMap:
            name: supported-accelerators
            items:
            - key: accelerators.json
              path: accelerators.json

