apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: operators
policyDefaults:
  namespace: cnfdf12-common
  policyAnnotations:
    ran.openshift.io/ztp-deploy-wave: '1'
  generatePolicyPlacement: true
policies:
  - name: operators
    manifests:
      - path: sriov-network-operator.v4.12.0-202302280915
      - path: ptp-operator.4.12.0-202303021731
      - path: local-storage-operator.v4.12.0-202302280915
      - path: cluster-logging.5.5.4
    remediationAction: inform
    placement:
      clusterSelector:
        matchExpressions:
          - key: common-cnfdf12
            operator: In
            values:
              - 'true'

