apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    creationTimestamp: null
    name: cluster-logging.v5.6.4-cluster-logging-operator-78f6785b45
rules:
    - apiGroups:
        - console.openshift.io
      resources:
        - consoleexternalloglinks
        - consoleplugins
        - consoleplugins/finalizers
      verbs:
        - '*'
    - apiGroups:
        - ""
      resources:
        - configmaps
      verbs:
        - '*'
    - apiGroups:
        - scheduling.k8s.io
      resources:
        - priorityclasses
      verbs:
        - '*'
    - apiGroups:
        - oauth.openshift.io
      resources:
        - oauthclients
      verbs:
        - '*'
    - apiGroups:
        - rbac.authorization.k8s.io
      resources:
        - clusterroles
        - clusterrolebindings
      verbs:
        - '*'
    - apiGroups:
        - config.openshift.io
      resources:
        - apiservers
        - clusterversions
        - proxies
        - infrastructures
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - security.openshift.io
      resources:
        - securitycontextconstraints
      verbs:
        - '*'
    - apiGroups:
        - ""
      resources:
        - pods
        - namespaces
        - services
        - services/finalizers
      verbs:
        - get
        - list
        - watch
