apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    creationTimestamp: null
    name: cluster-logging.v5.6.4-cluster-logging-operator-5845c7699f
    namespace: openshift-logging
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: cluster-logging.v5.6.4-cluster-logging-operator-5845c7699f
subjects:
    - kind: ServiceAccount
      name: cluster-logging-operator
      namespace: openshift-logging
