apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    creationTimestamp: null
    name: ptp-operator.4.12.0-202304111715-linuxptp-daemon-7cb7d9685
    namespace: openshift-ptp
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: ptp-operator.4.12.0-202304111715-linuxptp-daemon-7cb7d9685
subjects:
    - kind: ServiceAccount
      name: linuxptp-daemon
      namespace: openshift-ptp
