apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    creationTimestamp: null
    name: sriov-fec-metrics-reader
    namespace: vran-acceleration-operators
rules:
    - nonResourceURLs:
        - /metrics
      verbs:
        - get
