apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "ptp.openshift.io/v1",
          "kind": "NodePtpDevice",
          "metadata": {
            "name": "node.example.com"
          },
          "spec": {}
        },
        {
          "apiVersion": "ptp.openshift.io/v1",
          "kind": "PtpConfig",
          "metadata": {
            "name": "example-ptpconfig"
          },
          "spec": {
            "profile": [
              {
                "interface": "ens787f1",
                "name": "profile1",
                "phc2sysOpts": "-a -r",
                "ptp4lOpts": "-s -2",
                "ptpClockThreshold": {}
              }
            ],
            "recommend": [
              {
                "match": [
                  {
                    "nodeLabel": "node-role.kubernetes.io/worker=",
                    "nodeName": "node.example.com"
                  }
                ],
                "priority": 4,
                "profile": "profile1"
              }
            ]
          }
        },
        {
          "apiVersion": "ptp.openshift.io/v1",
          "kind": "PtpOperatorConfig",
          "metadata": {
            "name": "default"
          },
          "spec": {
            "daemonNodeSelector": {
              "feature.node.kubernetes.io/ptp-capable": "yes",
              "node-role.kubernetes.io/worker": ""
            },
            "ptpEventConfig": {}
          }
        }
      ]
    capabilities: Basic Install
    categories: Networking
    certified: "false"
    containerImage: registry.redhat.io/openshift4/ose-ptp-operator@sha256:2cb330ceb4a8399a8dc455c0fe98c78176c8c7532a7c6b7481189986919d7b75
    createdAt: "2019-10-14"
    description: This software enables configuration of Precision Time Protocol(PTP)
      on Kubernetes. It detects hardware capable PTP devices on each node, and configures
      linuxptp processes such as ptp4l, phc2sys and timemaster.
    olm.skipRange: '>=4.3.0-0 <4.12.0-202303021731'
    olm.targetNamespaces: openshift-ptp
    operators.openshift.io/infrastructure-features: '["disconnected"]'
    operators.openshift.io/valid-subscription: '["OpenShift Kubernetes Engine", "OpenShift
      Container Platform", "OpenShift Platform Plus"]'
    operators.operatorframework.io/builder: operator-sdk-v1.22.0-ocp
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
    provider: Red Hat
    repository: https://github.com/openshift/ptp-operator
    service.beta.openshift.io/serving-cert-secret-name: webhook-server-cert
    support: Red Hat
    target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
  creationTimestamp: null
  name: ptp-operator
  namespace: openshift-ptp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ptp-operator
  strategy: {}
  template:
    metadata:
      annotations:
        service.beta.openshift.io/serving-cert-secret-name: webhook-server-cert
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
      creationTimestamp: null
      labels:
        name: ptp-operator
    spec:
      containers:
      - args:
        - --enable-leader-election
        - --logtostderr
        - --stderrthreshold=INFO
        command:
        - ptp-operator
        env:
        - name: OPERATOR_NAME
          value: ptp-operator
        - name: RELEASE_VERSION
          value: v4.12.0
        - name: LINUXPTP_DAEMON_IMAGE
          value: registry.redhat.io/openshift4/ose-ptp@sha256:5006c73f8435d4e3a31db41fdf485760f9cdde5dd649759ac4b0ac4439ba4238
        - name: KUBE_RBAC_PROXY_IMAGE
          value: registry.redhat.io/openshift4/ose-kube-rbac-proxy@sha256:5df24a774bdcc0363e59bcf351806e6671e69d7553d9f123481a202558b83615
        - name: SIDECAR_EVENT_IMAGE
          value: registry.redhat.io/openshift4/ose-cloud-event-proxy@sha256:4013129d3cacaa7345e619376ce6e843f66b19c7dc7dccf0d34220bd88f62dd5
        - name: WATCH_NAMESPACE
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: registry.redhat.io/openshift4/ose-ptp-operator@sha256:2cb330ceb4a8399a8dc455c0fe98c78176c8c7532a7c6b7481189986919d7b75
        imagePullPolicy: IfNotPresent
        name: ptp-operator
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      nodeSelector:
        node-role.kubernetes.io/master: ""
      priorityClassName: system-node-critical
      serviceAccountName: ptp-operator
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: webhook-server-cert
status: {}
