resources:
    - daemonset-linuxptp-daemon.yaml
    - servicemonitor-monitor-ptp.yaml
    - service-ptp-monitor-service.yaml
    - role-prometheus-k8s.yaml
    - rolebinding-prometheus-k8s.yaml
    - prometheusrule-ptp-rules.yaml
    - namespace-openshift-ptp.yaml
