apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: ptp-operator.4.12.0-202303021731-ptp-operator-9df8d7d8d
  namespace: openshift-ptp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ptp-operator.4.12.0-202303021731-ptp-operator-9df8d7d8d
subjects:
- kind: ServiceAccount
  name: ptp-operator
  namespace: openshift-ptp
