apiVersion: v1
kind: Service
metadata:
    annotations:
        prometheus.io/scrape: "true"
        service.beta.openshift.io/serving-cert-secret-name: linuxptp-daemon-secret
    labels:
        name: ptp-monitor-service
    name: ptp-monitor-service
    namespace: openshift-ptp
spec:
    clusterIP: None
    ports:
        - name: metrics
          port: 8443
          targetPort: https
    selector:
        app: linuxptp-daemon
    sessionAffinity: None
    type: ClusterIP
