apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: fec
policies:
- manifests:
  - path: sriov-fec.v2.6.1
  name: fec
  placement:
    clusterSelector:
      matchExpressions:
      - key: common-cnfdf01
        operator: In
        values:
        - "true"
policyDefaults:
  namespace: cnfdf01-common
  placement: {}
  policyAnnotations:
    ran.openshift.io/ztp-deploy-wave: "1"
