apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    creationTimestamp: null
    name: local-storage-operator.v4.12.0-202302280915-local-st-7c99899f4f
    namespace: openshift-local-storage
rules:
    - apiGroups:
        - local.storage.openshift.io
      resources:
        - '*'
      verbs:
        - get
        - list
        - watch
        - create
        - update
