apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: local-storage-operator.v4.12.0-202302280915-local-st-7c99899f4f
  namespace: openshift-local-storage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: local-storage-operator.v4.12.0-202302280915-local-st-7c99899f4f
subjects:
- kind: ServiceAccount
  name: local-storage-admin
  namespace: openshift-local-storage
