apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    creationTimestamp: null
    name: local-storage-operator.v4.12.0-202304111715-local-sto-fd8bf8988
rules:
    - apiGroups:
        - storage.k8s.io
      resources:
        - storageclasses
      verbs:
        - '*'
    - apiGroups:
        - ""
      resources:
        - persistentvolumeclaims
        - events
      verbs:
        - '*'
    - apiGroups:
        - events.k8s.io
      resources:
        - events
      verbs:
        - '*'
    - apiGroups:
        - ""
      resources:
        - nodes
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - ""
      resources:
        - persistentvolumes
      verbs:
        - get
        - list
        - watch
        - create
        - delete
