apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    creationTimestamp: null
    name: local-storage-operator.v4.12.0-202304111715-local-st-66d67fc585
rules:
    - apiGroups:
        - security.openshift.io
      resourceNames:
        - privileged
      resources:
        - securitycontextconstraints
      verbs:
        - use
    - apiGroups:
        - ""
      resources:
        - nodes
      verbs:
        - list
        - get
        - watch
    - apiGroups:
        - ""
        - storage.k8s.io
      resources:
        - configmaps
        - storageclasses
        - persistentvolumeclaims
        - persistentvolumes
      verbs:
        - '*'
    - apiGroups:
        - ""
        - events.k8s.io
      resources:
        - events
      verbs:
        - get
        - list
        - watch
        - create
        - patch
        - update
    - apiGroups:
        - authentication.k8s.io
      resources:
        - tokenreviews
      verbs:
        - create
