apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    creationTimestamp: null
    name: local-storage-operator.v4.12.0-202304111715-local-sto-d4f65f8d5
    namespace: openshift-local-storage
rules:
    - apiGroups:
        - ""
        - coordination.k8s.io
      resources:
        - configmaps
        - leases
      verbs:
        - get
        - list
        - watch
        - create
        - update
        - patch
        - delete
    - apiGroups:
        - ""
      resources:
        - events
      verbs:
        - create
        - patch
    - apiGroups:
        - local.storage.openshift.io
      resources:
        - '*'
      verbs:
        - '*'
    - apiGroups:
        - ""
      resources:
        - pods
        - services
        - services/finalizers
        - endpoints
        - persistentvolumeclaims
        - events
        - configmaps
        - secrets
      verbs:
        - '*'
    - apiGroups:
        - apps
      resources:
        - deployments
        - daemonsets
        - replicasets
        - statefulsets
      verbs:
        - '*'
    - apiGroups:
        - events.k8s.io
      resources:
        - events
      verbs:
        - '*'
    - apiGroups:
        - monitoring.coreos.com
      resources:
        - servicemonitors
      verbs:
        - get
        - list
        - watch
        - create
        - update
        - patch
        - delete
    - apiGroups:
        - apps
      resourceNames:
        - local-storage-operator
      resources:
        - deployments/finalizers
      verbs:
        - update
