apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: local-storage-metrics
    namespace: openshift-local-storage
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: local-storage-metrics
subjects:
    - kind: ServiceAccount
      name: prometheus-k8s
      namespace: openshift-monitoring
