apiVersion: v1
kind: Service
metadata:
    creationTimestamp: null
    labels:
        control-plane: controller-manager
    name: sriov-fec-controller-manager-metrics-service
    namespace: vran-acceleration-operators
spec:
    ports:
        - name: https
          port: 8443
          targetPort: https
    selector:
        control-plane: controller-manager
