apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "1"
  labels:
    app: sriov-device-plugin-daemonset
  name: sriov-device-plugin
  namespace: openshift-sriov-fec
spec:
  minReadySeconds: 10
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sriov-device-plugin-daemonset
  template:
    metadata:
      labels:
        app: sriov-device-plugin-daemonset
    spec:
      containers:
      - args:
        - --log-level=10
        image: registry.redhat.io/openshift4/ose-sriov-network-device-plugin@sha256:1711cdb36e1eae979a65c9e6b7ab40f5193a8b5e5b6988b451ab8a925f94f561
        imagePullPolicy: IfNotPresent
        name: sriov-device-plugin
        resources: {}
        securityContext:
          privileged: true
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/kubelet/
          name: devicesock
        - mountPath: /etc/pcidp/
          name: config-volume
          readOnly: true
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        fpga.intel.com/intel-accelerator-present: ""
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: sriov-device-plugin
      serviceAccountName: sriov-device-plugin
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /var/lib/kubelet/
          type: ""
        name: devicesock
      - hostPath:
          path: /sys/class/net
          type: ""
        name: net
      - configMap:
          defaultMode: 420
          items:
          - key: config.json
            path: config.json
          name: sriovdp-config
        name: config-volume
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
