apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sriov-device-plugin
  namespace: openshift-sriov-fec
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sriov-plugin
subjects:
  - kind: ServiceAccount
    name: sriov-device-plugin
    namespace: openshift-sriov-fec

