apiVersion: v1
data:
  config.json: |
    {
        "resourceList": [
            {
                "resourceName": "intel_fec_lte",
                "deviceType": "accelerator",
                "selectors": {
                    "vendors": ["1172"],
                    "devices": ["5050"],
                    "drivers": ["pci-pf-stub", "vfio-pci"]
                }
            },
            {
                "resourceName": "intel_fec_5g",
                "deviceType": "accelerator",
                "selectors": {
                    "vendors": ["8086"],
                    "devices": ["0d90"],
                    "drivers": ["pci-pf-stub", "vfio-pci"]
                }
            },
            {
                "resourceName": "intel_fec_acc100",
                "deviceType": "accelerator",
                "selectors": {
                    "vendors": ["8086"],
                    "devices": ["0d5d"],
                    "drivers": ["pci-pf-stub", "vfio-pci"]
                }
            },
            {
            "resourceName": "intel_fec_acc200",
            "deviceType": "accelerator",
            "selectors": {
                "vendors": ["8086"],
                "devices": ["57c1"],
                "drivers": ["pci-pf-stub", "vfio-pci"]
            }
        }
        ]
    }
immutable: false
kind: ConfigMap
metadata:
  name: sriovdp-config
  namespace: openshift-sriov-fec
  