apiVersion: v1
kind: Service
metadata:
    annotations:
        service.beta.openshift.io/serving-cert-secret-name: sriov-fec-webhook-service
    creationTimestamp: null
    name: sriov-fec-webhook-service
    namespace: vran-acceleration-operators
spec:
    ports:
        - port: 443
          protocol: TCP
          targetPort: 9443
    selector:
        control-plane: controller-manager
