apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: {{.PolicyName}}
policyDefaults:
  namespace: {{.PolicyNamespace}}
  generatePolicyPlacement: true
policies:
  - name: {{.PolicyName}}
    manifests:
    {{range .Manifests}}
      - path: {{.}}
    {{end}}
    remediationAction: inform
    placement: {{.Placement}}

