---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: linuxptp-daemon
  namespace: openshift-ptp
  annotations:
    release.openshift.io/version: "{{.ReleaseVersion}}"
spec:
  selector:
    matchLabels:
      app: linuxptp-daemon
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 33%
  template:
    metadata:
      annotations:
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
      labels:
        app: linuxptp-daemon
    spec:
      hostNetwork: true
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
      - operator: Exists
      serviceAccountName: linuxptp-daemon
      priorityClassName: "system-node-critical"
      containers:
       {{ if (eq .EnableEventPublisher true) }}
        - name: cloud-event-proxy
          image: {{ .SideCar }}
          imagePullPolicy: IfNotPresent
          args:
            - "--metrics-addr=127.0.0.1:9091"
            - "--store-path=/store"
            - "--transport-host={{ .EventTransportHost }}"
            - "--api-port=9085"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/linuxptp
            - name: pubsubstore
              mountPath: /store
            - name: event-bus-socket
              mountPath: /cloud-native
            - name: socket-dir
              mountPath: /var/run
          ports:
            - name: metrics-port
              containerPort: 9091
            - name: api-port
              containerPort: 9085
          env:
            - name: PTP_PLUGIN
              value: "true"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
        {{ end }}
        - name: kube-rbac-proxy
          image: {{.KubeRbacProxy}}
          imagePullPolicy: IfNotPresent
          args:
            - --logtostderr
            - --secure-listen-address=:8443
            - --tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
            - --upstream=http://127.0.0.1:9091/
            - --tls-private-key-file=/etc/metrics/tls.key
            - --tls-cert-file=/etc/metrics/tls.crt
          ports:
            - containerPort: 8443
              name: https
          resources:
            requests:
              cpu: 10m
              memory: 20Mi
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - name: linuxptp-certs
              mountPath: /etc/metrics
              readOnly: True
        - name: linuxptp-daemon-container
          securityContext:
            privileged: true
          image: {{.Image}}
          imagePullPolicy: IfNotPresent
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "/usr/local/bin/ptp --alsologtostderr -v 10" ]
          resources:
            requests:
              cpu: 20m
              memory: 50Mi
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: LOGS_TO_SOCKET
              value: "{{ .EnableEventPublisher }}"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/linuxptp
            - name: socket-dir
              mountPath: /var/run
            {{ if (eq .EnableEventPublisher true) }}
            - name: event-bus-socket
              mountPath: /cloud-native
            {{ end }}
      volumes:
        - name: config-volume
          configMap:
            name: ptp-configmap
        - name: linuxptp-certs
          secret:
            secretName: linuxptp-daemon-secret
        {{ if (eq .EnableEventPublisher true) }}
        - name: pubsubstore
          emptyDir: {}
        - name: event-bus-socket
          emptyDir: {}
        {{ end }}
        - name: socket-dir
          hostPath:
            path: /var/run/ptp
            type: DirectoryOrCreate
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    name: monitor-ptp
  name: monitor-ptp
  namespace: openshift-ptp
spec:
  endpoints:
    - interval: 30s
      port: metrics
      bearerTokenFile: "/var/run/secrets/kubernetes.io/serviceaccount/token"
      scheme: "https"
      tlsConfig:
        caFile: "/etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt"
        serverName: "ptp-monitor-service.{{.Namespace}}.svc"
  jobLabel: app
  namespaceSelector:
    matchNames:
      - openshift-ptp
  selector:
    matchLabels:
      name: ptp-monitor-service
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    service.beta.openshift.io/serving-cert-secret-name: linuxptp-daemon-secret
  labels:
    name: ptp-monitor-service
  name:  ptp-monitor-service
  namespace: openshift-ptp
spec:
  selector:
    app: linuxptp-daemon
  clusterIP: None
  ports:
    - name: metrics
      port: 8443
      targetPort: https
  sessionAffinity: None
  type: ClusterIP
  {{ if (eq .EnableEventPublisher true) }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "false"
    service.beta.openshift.io/serving-cert-secret-name: linuxptp-daemon-secret
  labels:
    app: linuxptp-daemon
  name:  ptp-event-publisher-service
  namespace: openshift-ptp
spec:
  selector:
    app: linuxptp-daemon
  clusterIP: None
  ports:
    - name: publisher-port
      port: 9043
  sessionAffinity: None
  type: ClusterIP
  {{ end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-k8s
  namespace: openshift-ptp
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - pods
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-k8s
  namespace: openshift-ptp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-k8s
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: openshift-monitoring
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: ptp-rules
  namespace: openshift-ptp
spec:
  groups:
    - name: ptp.rules
      rules:
        {{ if (eq .EnableEventPublisher true) }}
        - alert: NodeOutOfPtpSync
          annotations:
            message: |
              {{ "{{" }} $labels.iface }} is not in sync
          expr: |
            openshift_ptp_clock_state != 1
          for: 2m
          labels:
            severity: warning
        {{ end }}
        {{ if (eq .EnableEventPublisher false) }}
        - alert: HighPtpSyncOffset
          annotations:
            message: |
              All nodes should have ptp sync offset lower then 100
          expr: |
            openshift_ptp_offset_ns > 100 or openshift_ptp_offset_ns < -100
          for: 2m
          labels:
            severity: warning
        {{ end }}
---
apiVersion: v1
data:
  cnfdf12: '[{"name":"oc-1","interface":"ens1f0","phc2sysOpts":"-a
    -r -m -n 24 --step_threshold 2.0","ptpSchedulingPolicy":"SCHED_FIFO","ptpSchedulingPriority":32,
    "ptp4lOpts":"-2 -s", "ptp4lConf":"[global]\n#\n# Default Data Set\n#\ntwoStepFlag 1\nslaveOnly
    0\npriority1 128\npriority2 128\ndomainNumber 24\n#utc_offset 37\nclockClass 255\nclockAccuracy
    0xFE\noffsetScaledLogVariance 0xFFFF\nfree_running 0\nfreq_est_interval 1\ndscp_event
    0\ndscp_general 0\ndataset_comparison G.8275.x\nG.8275.defaultDS.localPriority
    128\n#\n# Port Data Set\n#\nlogAnnounceInterval -3\nlogSyncInterval -4\nlogMinDelayReqInterval
    -4\nlogMinPdelayReqInterval -4\nannounceReceiptTimeout 3\nsyncReceiptTimeout 0\ndelayAsymmetry
    0\nfault_reset_interval 4\nneighborPropDelayThresh 20000000\nmasterOnly 0\nG.8275.portDS.localPriority
    128\n#\n# Run time options\n#\nassume_two_step 0\nlogging_level 6\npath_trace_enabled
    0\nfollow_up_info 0\nhybrid_e2e 0\ninhibit_multicast_service 0\nnet_sync_monitor
    0\ntc_spanning_tree 0\ntx_timestamp_timeout 50\nunicast_listen 0\nunicast_master_table
    0\nunicast_req_duration 3600\nuse_syslog 1\nverbose 0\nsummary_interval 0\nkernel_leap
    1\ncheck_fup_sync 0\n#\n# Servo Options\n#\npi_proportional_const 0.0\npi_integral_const
    0.0\npi_proportional_scale 0.0\npi_proportional_exponent -0.3\npi_proportional_norm_max
    0.7\npi_integral_scale 0.0\npi_integral_exponent 0.4\npi_integral_norm_max 0.3\nstep_threshold
    2.0\nfirst_step_threshold 0.00002\nmax_frequency 900000000\nclock_servo pi\nsanity_freq_limit
    200000000\nntpshm_segment 0\n#\n# Transport options\n#\ntransportSpecific 0x0\nptp_dst_mac
    01:1B:19:00:00:00\np2p_dst_mac 01:80:C2:00:00:0E\nudp_ttl 1\nudp6_scope 0x0E\nuds_address
    /var/run/ptp4l\n#\n# Default interface options\n#\nclock_type OC\nnetwork_transport
    L2\ndelay_mechanism E2E\ntime_stamping hardware\ntsproc_mode filter\ndelay_filter
    moving_median\ndelay_filter_length 10\negressLatency 0\ningressLatency 0\nboundary_clock_jbod
    0\n#\n# Clock description\n#\nproductDescription ;;\nrevisionData ;;\nmanufacturerIdentity
    00:00:00\nuserDescription ;\ntimeSource 0xA0\n"}]'
kind: ConfigMap
metadata:
  name: ptp-configmap
  namespace: openshift-ptp