apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    openshift.io/scc: sriov-fec-daemon
  labels:
    app: sriov-fec-daemonset
  name: sriov-fec-daemonset
  namespace: openshift-sriov-fec
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sriov-fec-daemonset
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        app: sriov-fec-daemonset
    spec:
      containers:
      - env:
        - name: SRIOV_FEC_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: NODENAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: DRAIN_TIMEOUT_SECONDS
          value: "90"
        - name: LEASE_DURATION_SECONDS
          value: "600"
        image: registry.connect.redhat.com/intel/sriov-fec-daemon@sha256:671498e02c3003e2f503f3e0a65a28d0e6440124da2211ccabb9af7d47155ff0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        name: sriov-fec-daemon
        ports:
        - containerPort: 8080
          name: bbdevconfig
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          privileged: true
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /dev/vfio
          name: devvfio
          readOnly: true
        - mountPath: /sriov_config/
          name: vfiotoken
          readOnly: true
        - mountPath: /lib/modules
          name: libmodules
        - mountPath: /sriov_config/config
          name: config-volume
          readOnly: true
        - mountPath: /var/log
          name: logs
        - mountPath: /tmp
          name: tmp
      dnsPolicy: Default
      nodeSelector:
        fpga.intel.com/intel-accelerator-present: ""
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: sriov-fec-daemon
      serviceAccountName: sriov-fec-daemon
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: intel.com/sriovfec
        operator: Exists
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: accelerators.json
            path: accelerators.json
          name: supported-accelerators
        name: config-volume
      - name: vfiotoken
        secret:
          defaultMode: 420
          items:
          - key: VFIO_TOKEN
            path: vfiotoken
          optional: false
          secretName: vfio-token
      - hostPath:
          path: /dev/vfio
          type: ""
        name: devvfio
      - hostPath:
          path: /lib/modules
          type: ""
        name: libmodules
      - emptyDir: {}
        name: logs
      - emptyDir: {}
        name: tmp
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate

