apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sriov-fec-daemon
  namespace: openshift-sriov-fec
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sriov-fec-daemon
subjects:
- kind: ServiceAccount
  name: sriov-fec-daemon
  namespace: openshift-sriov-fec

  

