apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    creationTimestamp: null
    name: prometheus
    namespace: openshift-logging
rules:
    - apiGroups:
        - ""
      resources:
        - pods
        - services
        - endpoints
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - ""
      resources:
        - configmaps
      verbs:
        - get
