apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: cluster-logging.5.5.4-cluster-logging-operator-58cd59778b
  namespace: openshift-logging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cluster-logging.5.5.4-cluster-logging-operator-58cd59778b
subjects:
- kind: ServiceAccount
  name: cluster-logging-operator
  namespace: openshift-logging
