apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "sriovnetwork.openshift.io/v1",
          "kind": "SriovIBNetwork",
          "metadata": {
            "name": "example-sriovibnetwork",
            "namespace": "openshift-sriov-network-operator"
          },
          "spec": {
            "ipam": "{\n  \"type\": \"host-local\",\n  \"subnet\": \"10.56.217.0/24\",\n  \"rangeStart\": \"10.56.217.171\",\n  \"rangeEnd\": \"10.56.217.181\",\n  \"routes\": [{\n    \"dst\": \"0.0.0.0/0\"\n  }],\n  \"gateway\": \"10.56.217.1\"\n}\n",
            "linkState": "auto",
            "networkNamespace": "default",
            "resourceName": "mellanoxnics"
          }
        },
        {
          "apiVersion": "sriovnetwork.openshift.io/v1",
          "kind": "SriovNetwork",
          "metadata": {
            "name": "example-sriovnetwork",
            "namespace": "openshift-sriov-network-operator"
          },
          "spec": {
            "ipam": "{\n  \"type\": \"host-local\",\n  \"subnet\": \"10.56.217.0/24\",\n  \"rangeStart\": \"10.56.217.171\",\n  \"rangeEnd\": \"10.56.217.181\",\n  \"routes\": [{\n    \"dst\": \"0.0.0.0/0\"\n  }],\n  \"gateway\": \"10.56.217.1\"\n}\n",
            "networkNamespace": "default",
            "resourceName": "intelnics",
            "spoofChk": "on",
            "trust": "off",
            "vlan": 0
          }
        },
        {
          "apiVersion": "sriovnetwork.openshift.io/v1",
          "kind": "SriovNetworkNodePolicy",
          "metadata": {
            "name": "policy-1",
            "namespace": "openshift-sriov-network-operator"
          },
          "spec": {
            "deviceType": "vfio-pci",
            "mtu": 9000,
            "nicSelector": {
              "pfNames": [
                "eth1"
              ],
              "rootDevices": [
                "0000:01:00.1"
              ],
              "vendor": "8086"
            },
            "nodeSelector": {
              "feature.node.kubernetes.io/network-sriov.capable": "true"
            },
            "numVfs": 6,
            "priority": 99,
            "resourceName": "intelnics"
          }
        },
        {
          "apiVersion": "sriovnetwork.openshift.io/v1",
          "kind": "SriovNetworkNodeState",
          "metadata": {
            "name": "minikube",
            "namespace": "openshift-sriov-network-operator"
          },
          "spec": {
            "interfaces": []
          }
        },
        {
          "apiVersion": "sriovnetwork.openshift.io/v1",
          "kind": "SriovNetworkPoolConfig",
          "metadata": {
            "name": "sriovnetworkpoolconfig-sample"
          },
          "spec": {
            "foo": "bar"
          }
        },
        {
          "apiVersion": "sriovnetwork.openshift.io/v1",
          "kind": "SriovOperatorConfig",
          "metadata": {
            "name": "default",
            "namespace": "openshift-sriov-network-operator"
          },
          "spec": {
            "enableInjector": true,
            "enableOperatorWebhook": true,
            "logLevel": 2
          }
        }
      ]
    capabilities: Basic Install
    categories: Networking
    certified: "false"
    containerImage: quay.io/pliurh/sriov-network-operator-manager:bd1
    createdAt: 2019/04/30
    description: An operator for configuring SR-IOV components and initializing SRIOV
      network devices in Openshift cluster.
    olm.skipRange: '>=4.3.0-0 <4.12.0-202302280915'
    olm.targetNamespaces: openshift-sriov-network-operator
    operatorframework.io/suggested-namespace: openshift-sriov-network-operator
    operators.openshift.io/infrastructure-features: '["disconnected", "cni"]'
    operators.openshift.io/valid-subscription: '["OpenShift Kubernetes Engine", "OpenShift
      Container Platform", "OpenShift Platform Plus"]'
    operators.operatorframework.io/builder: operator-sdk-v1.23.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
    repository: https://github.com/k8snetworkplumbingwg/sriov-network-operator
    support: Red Hat
    target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
  creationTimestamp: null
  labels:
    control-plane: controller-manager
  name: sriov-network-operator
  namespace: openshift-sriov-network-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sriov-network-operator
  strategy: {}
  template:
    metadata:
      annotations:
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
      creationTimestamp: null
      labels:
        name: sriov-network-operator
    spec:
      containers:
      - args:
        - --leader-elect
        command:
        - sriov-network-operator
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['olm.targetNamespaces']
        - name: SRIOV_CNI_IMAGE
          value: registry.redhat.io/openshift4/ose-sriov-cni@sha256:9460fc555fda76144481f2e07f66356753390fd174f7a7a68540c254edb8d992
        - name: SRIOV_DEVICE_PLUGIN_IMAGE
          value: registry.redhat.io/openshift4/ose-sriov-network-device-plugin@sha256:2f8af15a91bc5b05aeeb8c85bd23fabfbdb676e0bb087cfe83158665123b6c63
        - name: NETWORK_RESOURCES_INJECTOR_IMAGE
          value: registry.redhat.io/openshift4/ose-sriov-dp-admission-controller@sha256:f0c930e3cd5d0acf906b2c48cd03bdb2049a3a76c0aca7c1885c0ac4dacf10fe
        - name: OPERATOR_NAME
          value: sriov-network-operator
        - name: SRIOV_NETWORK_CONFIG_DAEMON_IMAGE
          value: registry.redhat.io/openshift4/ose-sriov-network-config-daemon@sha256:2745ae21d286e385bc63f8356a5bccf9d40bd12a8dd41b5b4f03b455f49100a3
        - name: SRIOV_NETWORK_WEBHOOK_IMAGE
          value: registry.redhat.io/openshift4/ose-sriov-network-webhook@sha256:439b9927b56f8ff9bc11eaef61f70d27db7b9efe33d07dd5b008d2a3bd39c581
        - name: SRIOV_INFINIBAND_CNI_IMAGE
          value: registry.redhat.io/openshift4/ose-sriov-infiniband-cni@sha256:c143248fb6f946adc9f9018c7422b9b93b860d37e9d73a32efb2c5e0bdc2ac64
        - name: RESOURCE_PREFIX
          value: openshift.io
        - name: ENABLE_ADMISSION_CONTROLLER
          value: "true"
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: RELEASE_VERSION
          value: 4.12.0
        image: registry.redhat.io/openshift4/ose-sriov-network-operator@sha256:7f8afd6678cf5bd91d301a9637bf86747f8b2c7afdd1e6605547e67d27981f37
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: sriov-network-operator
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {}
      nodeSelector:
        node-role.kubernetes.io/master: ""
      serviceAccountName: sriov-network-operator
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
status: {}
