apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: sriov-network-operator.v4.12.0-202302280915-sriov-ne-5fbc664758
  namespace: openshift-sriov-network-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sriov-network-operator.v4.12.0-202302280915-sriov-ne-5fbc664758
subjects:
- kind: ServiceAccount
  name: sriov-network-config-daemon
  namespace: openshift-sriov-network-operator
