apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    creationTimestamp: null
    name: metadata-reader
    namespace: openshift-logging
rules:
    - apiGroups:
        - ""
      resources:
        - pods
        - namespaces
        - nodes
      verbs:
        - get
        - list
        - watch
