apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        alm-examples: |-
            [
              {
                "apiVersion": "logging.openshift.io/v1",
                "kind": "ClusterLogForwarder",
                "metadata": {
                  "name": "instance",
                  "namespace": "openshift-logging"
                },
                "spec": {
                  "outputs": [
                    {
                      "name": "remote-elasticsearch",
                      "secret": {
                        "name": "elasticsearch"
                      },
                      "type": "elasticsearch",
                      "url": "remote.example.org:9200"
                    }
                  ],
                  "pipelines": [
                    {
                      "inputRefs": [
                        "application",
                        "audit",
                        "infrastructure"
                      ],
                      "name": "enable-default-log-store",
                      "outputRefs": [
                        "default"
                      ]
                    },
                    {
                      "inputRefs": [
                        "application"
                      ],
                      "name": "forward-to-remote",
                      "outputRefs": [
                        "remote-elasticsearch"
                      ]
                    }
                  ]
                }
              },
              {
                "apiVersion": "logging.openshift.io/v1",
                "kind": "ClusterLogging",
                "metadata": {
                  "name": "instance",
                  "namespace": "openshift-logging"
                },
                "spec": {
                  "collection": {
                    "type": "fluentd"
                  },
                  "logStore": {
                    "elasticsearch": {
                      "nodeCount": 3,
                      "redundancyPolicy": "SingleRedundancy",
                      "resources": {
                        "requests": {
                          "memory": "2Gi"
                        }
                      },
                      "storage": {
                        "size": "200G",
                        "storageClassName": "gp2"
                      }
                    },
                    "retentionPolicy": {
                      "application": {
                        "maxAge": "7d"
                      }
                    },
                    "type": "elasticsearch"
                  },
                  "managementState": "Managed",
                  "visualization": {
                    "kibana": {
                      "replicas": 1
                    },
                    "type": "kibana"
                  }
                }
              }
            ]
        capabilities: Seamless Upgrades
        categories: OpenShift Optional, Logging & Tracing
        certified: "false"
        console.openshift.io/plugins: '["logging-view-plugin"]'
        containerImage: registry.redhat.io/openshift-logging/cluster-logging-rhel8-operator@sha256:a8831cd43ff166a938f7ddfc81562e5d44f556f634e84ef11d2429e57279c9c0
        createdAt: "2018-08-01T08:00:00Z"
        description: The Red Hat OpenShift Logging Operator for OCP provides a means for configuring and managing your aggregated logging stack.
        kubectl.kubernetes.io/default-container: cluster-logging-operator
        olm.skipRange: '>=4.6.0-0 <5.6.3'
        olm.targetNamespaces: openshift-logging
        operatorframework.io/cluster-monitoring: "true"
        operatorframework.io/suggested-namespace: openshift-logging
        operators.openshift.io/infrastructure-features: '["disconnected","proxy-aware"]'
        operators.openshift.io/valid-subscription: '["OpenShift Kubernetes Engine", "OpenShift Container Platform", "OpenShift Platform Plus"]'
        operators.operatorframework.io/builder: operator-sdk-unknown
        operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
        support: AOS Logging (team-logging@redhat.com)
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
    creationTimestamp: null
    name: cluster-logging-operator
    namespace: openshift-logging
spec:
    replicas: 1
    selector:
        matchLabels:
            name: cluster-logging-operator
    strategy: {}
    template:
        metadata:
            annotations:
                kubectl.kubernetes.io/default-container: cluster-logging-operator
                target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
            creationTimestamp: null
            labels:
                name: cluster-logging-operator
        spec:
            containers:
                - command:
                    - cluster-logging-operator
                  env:
                    - name: WATCH_NAMESPACE
                      valueFrom:
                        fieldRef:
                            fieldPath: metadata.annotations['olm.targetNamespaces']
                    - name: POD_NAME
                      valueFrom:
                        fieldRef:
                            fieldPath: metadata.name
                    - name: OPERATOR_NAME
                      value: cluster-logging-operator
                    - name: RELATED_IMAGE_VECTOR
                      value: registry.redhat.io/openshift-logging/vector-rhel8@sha256:eaa919745da8281aadd7044586590a98729e1b997ebd55e24c45cf2d90b75f23
                    - name: RELATED_IMAGE_FLUENTD
                      value: registry.redhat.io/openshift-logging/fluentd-rhel8@sha256:792f9f148cf39092a406638ba3c6cc2b46cb4bc81e171338dafbb8b05dfa362f
                    - name: RELATED_IMAGE_LOG_FILE_METRIC_EXPORTER
                      value: registry.redhat.io/openshift-logging/log-file-metric-exporter-rhel8@sha256:4cdf11ec57f20c3d74ebd6ff33abd8807a67ef0e9da5b5f818a786b7aca191e2
                    - name: RELATED_IMAGE_LOGGING_CONSOLE_PLUGIN
                      value: registry.redhat.io/openshift-logging/logging-view-plugin-rhel8@sha256:0dc61c30a084f157b2075cadcb1b56db421e1ada6c1fbf2a6394824e9fd167d8
                  image: registry.redhat.io/openshift-logging/cluster-logging-rhel8-operator@sha256:a8831cd43ff166a938f7ddfc81562e5d44f556f634e84ef11d2429e57279c9c0
                  imagePullPolicy: IfNotPresent
                  name: cluster-logging-operator
                  resources: {}
                  securityContext:
                    allowPrivilegeEscalation: false
                    capabilities:
                        drop:
                            - ALL
            nodeSelector:
                kubernetes.io/os: linux
            securityContext:
                runAsNonRoot: true
            serviceAccountName: cluster-logging-operator
