apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    creationTimestamp: null
    name: cluster-logging.v5.6.3-cluster-logging-operator-8998dc6b4
    namespace: openshift-logging
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: cluster-logging.v5.6.3-cluster-logging-operator-8998dc6b4
subjects:
    - kind: ServiceAccount
      name: cluster-logging-operator
      namespace: openshift-logging
